export const enum EventType {
  ANIMAL_BORN = 'ANIMAL_BORN',
  ANIMAL_DIED = 'ANIMAL_DIED',
  AIR_CLEANED = 'AIR_CLEANED',
  AIR_POLLUTED = 'AIR_POLLUTED',
  FOREST_SAVED = 'FOREST_SAVED',
  FOREST_DESTROYED = 'FOREST_DESTROYED',
  WATER_CLEANED = 'WATER_CLEANED',
  WATER_POLLUTED = 'WATER_POLLUTED',
  DAILY_QUESTION = 'DAILY_QUESTION'
}
